//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerFlipkartdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int SuppId { get; set; }
        public string SuppName { get; set; }
        public int SupplierAddress_StreetNo { get; set; }
        public string SupplierAddress_StreetName { get; set; }
        public int SupplierAddress_BldgNo { get; set; }
        public string SupplierAddress_SocietyName { get; set; }
        public string SupplierAddress_City { get; set; }
        public string SupplierAddress_State { get; set; }
        public string SupplierAddress_Country { get; set; }
        public string SupplierAddress_Pincode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
